### ISSUE TITLE
python error running on macOS

### ISSUE THREAD

**Issue by gioman** [planetfederal/qgis-reports-plugin#3] opened 2017-07-01 01:21 UTC
tested on b1 installer and macOS 10.12.5

```
Traceback (most recent call last):
  File "/Library/Boundless/Desktop/1.1/Cellar/qgis2-bdesk/2.18.10/QGIS.app/Contents/MacOS/../Resources/python/plugins/reportingtool/plugin.py", line 107, in run
    filePath = self.lastReport()
  File "/Library/Boundless/Desktop/1.1/Cellar/qgis2-bdesk/2.18.10/QGIS.app/Contents/MacOS/../Resources/python/plugins/reportingtool/plugin.py", line 123, in lastReport
    return reports[-1][1]
IndexError: list index out of range
```

**Comment by gioman** [comment] 2017-07-01 17:43
@alexbruy tried the latest commit upgrading from dev repo

```
IndexError: list index out of range 
Traceback (most recent call last):
  File "/Users/gmanghi/.qgis2/python/plugins/reportingtool/plugin.py", line 112, in run
    report, filePath = createReport()
  File "/Users/gmanghi/.qgis2/python/plugins/reportingtool/ext-libs/qgissysinfo/createreport.py", line 49, in createReport
    report = qgissysinfo.info_as_text()
  File "/Users/gmanghi/.qgis2/python/plugins/reportingtool/ext-libs/qgissysinfo/__init__.py", line 31, in info_as_text
    return _as_text(info())
  File "/Users/gmanghi/.qgis2/python/plugins/reportingtool/ext-libs/qgissysinfo/__init__.py", line 8, in info
    _info = systeminfo.allSystemInfo()
  File "/Users/gmanghi/.qgis2/python/plugins/reportingtool/ext-libs/qgissysinfo/systeminfo.py", line 62, in allSystemInfo
    info = systemInfo()
  File "/Users/gmanghi/.qgis2/python/plugins/reportingtool/ext-libs/qgissysinfo/systeminfo.py", line 81, in systemInfo
    "Processor": _cpuInfo(),
  File "/Users/gmanghi/.qgis2/python/plugins/reportingtool/ext-libs/qgissysinfo/systeminfo.py", line 173, in _cpuInfo
    info = subprocess.check_output("sysctl -n machdep.cpu.brand_string", shell=True, universal_newlines=True).split(":")[1].strip()
IndexError: list index out of range
```

**Comment by alexbruy** [comment] 2017-07-03 08:03
Last error caused by changes in `sysctl` output. Should be fixed now, please retest

**Comment by gioman** [comment] 2017-07-05 12:24
@alexbruy @luipir I guess this can be closed? This has been re-tested on macOS?

**Comment by luipir** [comment] 2017-07-05 13:06
correct

**Closed as completed by luipir** 2017-07-05 13:06 UTC
Labels: bug
